### PR TITLE
Xml Model Change: Adds action in detail field

### PR DESCRIPTION
**Pull request by shubham1g5**
## Product Description
[Spec](https://docs.google.com/document/d/1coxsFVCYgaQdxE3rgYikRSgEgistrfIUJuoW5KMiM5w/edit)

[HQ PR](https://github.com/dimagi/commcare-hq/pull/33543)

### Safety story

Only Model Change, Functional changes will be part of separate PR

### Automated test coverage

Covered with a new test.

### QA Plan
None

### Special deploy instructions

- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations.

### Review

- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### Duplicate PR
Automatically duplicate this PR as defined in [contributing.md](https://github.com/dimagi/commcare-core/blob/master/.github/contributing.md).

### CODE REVIEW

**Review by MartinRiese — APPROVED** [review]

**Review by Robert-Costello — APPROVED** [review]

**Comment by shubham1g5** [comment]
duplicate this PR

**Comment by shubham1g5** [comment]
duplicate this PR

**Comment by shubham1g5** [comment]
duplicate this PR 962732900d7f6a998d2f137b4275c67443cdb410

**Comment by shubham1g5** [comment]
duplicate this PR

**Comment by shubham1g5** [comment]
duplicate this PR https://github.com/dimagi/commcare-core/commit/962732900d7f6a998d2f137b4275c67443cdb410

**Comment by shubham1g5** [comment]
@shubham1g5 to duplication failure on this PR

**Pull request merged**
