### PR TITLE
Gradle 7 Compatibility Update

### PR DESCRIPTION
**Pull request by ctsims**

### CODE REVIEW

**Comment by ctsims** [comment]
@damagatchi retest this please

**Review by snopoke — DISMISSED** [review]

**Comment by ShivamPokhriyal** [comment]
@ctsims I did some work on AGP upgrade here https://github.com/dimagi/commcare-core/pull/1034 and https://github.com/dimagi/commcare-android/pull/2526. Can you probably try that out and see whether they work?

**Comment by shubham1g5** [comment]
yup, I am currently working on testing those PRs. Going to close this for now.

**Comment by ShivamPokhriyal** [comment]
Awesome, thanks @shubham1g5! I just saw some unaddressed comments on one of those PR. I'll try to reply to those by tomorrow.

**Pull request closed without merging**
