### PR TITLE
Enable showing actions in the app bar

### PR DESCRIPTION
**Pull request by amstone326**

### CODE REVIEW

**Comment by phillipm** [comment]
Can you include test coverage to the parser extensions added in this PR?

**Comment by amstone326** [comment]
@phillipm Hey, I'm actually not seeing anywhere that we have existing tests for parsing actions at all. Did you have a set of tests in mind to be adding to, or just assuming that it was somewhere?

**Comment by phillipm** [comment]
[SessionStackTests](https://github.com/dimagi/commcare-core/blob/master/tests/test/org/commcare/backend/session/test/SessionStackTests.java#L273) has several tests that check behavior of actions

**Comment by amstone326** [comment]
@phillipm Test added

**Pull request merged**
