### PR TITLE
Remove readonly ODK attribute

### PR DESCRIPTION
**Pull request by wpride**
#kill unused/annoying `readonly` attribute inherited from ODK

### CODE REVIEW

**Comment by shubham1g5** [comment]
It looks like a useful flag to me. Is there a reason we don't want to support this ?

**Comment by wpride** [comment]
@shubham1g5 Mostly because as far as I know we're not using it (though this might be good to double check now that I think about it) and YAGNI

**Comment by ctsims** [comment]
Hey, so this isn't an ODK inherited thing, this is part of the xforms spec

https://www.w3.org/TR/2001/WD-xforms-20010828/slice5.html#model-prop-readOnly

I'm opposed to removing things that are spec compliant, even if we aren't specifically using them, unless they are causing serious issues

**Comment by amstone326** [comment]
@wpride can this be killed based on the above comments?

**Pull request closed without merging**
