### PR TITLE
Clickable Icon UI

### PR DESCRIPTION
**Pull request by MartinRiese**
## Technical Summary

https://dimagi-dev.atlassian.net/browse/USH-3698?atlOrigin=eyJpIjoiMTc0NDJiYTdhNDdiNGUzMDg1NjIzNzdhNjkwZGI3MjMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ

### Special deploy instructions

- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations.

### Review

- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### Duplicate PR
Automatically duplicate this PR as defined in [contributing.md](https://github.com/dimagi/commcare-core/blob/master/.github/contributing.md).

### CODE REVIEW

**Review by shubham1g5 — APPROVED** [review]

**Comment by Robert-Costello** [comment]
@shubham1g5 This still needs a duplicate PR on the formplayer branch, correct?

**Comment by shubham1g5** [comment]
yes

**Comment by shubham1g5** [comment]
duplicate this PR 7055c5934d8473ce73b9b41ef2c6b2e8848b0439

**Comment by Jtang-1** [comment]
duplicate this PR 7055c59 7055c59

**Comment by Jtang-1** [comment]
duplicate this PR 7055c59 7055c59

**Pull request merged**
