### PR TITLE
Fix for J2ME Calculated Session Data

### PR DESCRIPTION
**Pull request by ctsims**
Fixes a bug where the new polymorphic session datum types weren't working right on j2me.

Fix for:
http://manage.dimagi.com/default.asp?230701

### CODE REVIEW

**Comment by ctsims** [comment]
@phillipm What is the right process to follow for this to get into new-j2me as well?

**Comment by phillipm** [comment]
To get javarosa j2me changes into 2.28 and any j2me related changes into
the new j2me repo you will need to create a PR in the commcare-j2me repo

**Comment by ctsims** [comment]
@phillipm Cool. This one is a commcare change for 2.28, so I think it still goes here. I'll make a duplicate change in commcare-j2me for future releases on j2me.

**Comment by ctsims** [comment]
@phillipm Great, replicated here: https://github.com/dimagi/commcare-j2me/pull/315

**Pull request merged**
