### PR TITLE
Changed fromMillis to work with calls coming from commcare-android

### PR DESCRIPTION
**Pull request by RynhardPietersen**
## Product Description

Follow up pr from [here](https://github.com/dimagi/commcare-core/commit/0d484e24e8d0e108611845c2a292042bd8e75f26). 

## Technical Summary

Calls from commcare-android require fromMIllis to accept a `long` variable and so this change addresses that.

### Safety story

local testing

### Special deploy instructions

- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations.

### Review

- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### CODE REVIEW

**Review by avazirna — APPROVED** [review]
Looks good to me but Stickler doesn't look happy :-)

**Review by shubham1g5 — APPROVED** [review]
looks good but we need to duplicate this PR for `formplayer` as well.

**Comment by RynhardPietersen** [comment]
Closing this because I meant to make formplayer the base but I instead made master the base and then merged master into my branch.

**Comment by shubham1g5** [comment]
@RynhardPietersen this should not be closed. We need this change in both `master` and `formplayer`. So we should create 2 PRs one targetting to `master` and other to `formplayer`

**Review by shubham1g5 — APPROVED** [review]

**Pull request merged**
