### PR TITLE
exclude user input from search filter

### PR DESCRIPTION
**Pull request by Robert-Costello**
Changes merged into formplayer branch https://github.com/dimagi/commcare-core/pull/1085

[Spec for this feature](https://docs.google.com/document/d/1FeHaa1JoA6NCRJfPX8Nt3joOAlqzFEgpT0NKlZkgy1I/edit#)
[Related HQ PR](https://github.com/dimagi/commcare-hq/pull/31205)
image

### CODE REVIEW

**Comment by Robert-Costello** [comment]
@orangejenny @snopoke Correct me if I'm wrong, but closing this PR and makings changes in a branch built off of Master seems like the necessary move here.

**Comment by orangejenny** [comment]
It looks like this branch is based off of formplayer (which is right) so you'll want to change the PR to merge into formplayer. That'll reduce the diff down to your actual changes.

**Comment by orangejenny** [comment]
yeah, you should be able to just edit this PR to switch the base branch

**Comment by Robert-Costello** [comment]
Just to make sure I understand and we're on the same page, I've merged my changes into the formplayer branch already here: https://github.com/dimagi/commcare-core/pull/1085. This was intended to be the second PR against master.

**Comment by orangejenny** [comment]
oops, I was not on the same page. yeah, making the changes in a branch based on master is the thing to do. I usually do this by using `git cherry-pick` each commit for each commit from the original PR, resolving any conflicts that come up.

**Pull request closed without merging**
