### PR TITLE
[NOTE - Needs HotFix] XPath Message formatting error

### PR DESCRIPTION
**Pull request by ctsims**
Fix and test for a bug introduced in https://github.com/dimagi/commcare-core/pull/483 

NOTE: this should get hotfixed back to 2.32, and we should test whether that PR has any similar issues (they may have been copy/pasted)

### CODE REVIEW

**Comment by snopoke** [comment]
Thanks and sorry. Re-checked the other PR and didn't see any other issues. It would be the one error I didn't test locally :(

**Comment by ctsims** [comment]
@snopoke It happens to all of us, thanks for reviewing the other push!

**Comment by amstone326** [comment]
FYI to all that no hotfix is needed, the original PR never made it's way into 2.32 in the first place

**Comment by ctsims** [comment]
🎉🎉🎉 Woo! For some reason I thought I remembered the error msg thing getting pulled

**Comment by czue** [comment]
nice! here I was thinking that @snopoke was going to sabotage the mobile team's hot streak... :smiling_imp:

**Pull request merged**
