### PR TITLE
Stickler Checks and Updates Checkstyle

### PR DESCRIPTION
**Pull request by shubham1g5**
Updates the checkstyle to match https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

### CODE REVIEW

**Comment by shubham1g5** [comment]
test

**Comment by shubham1g5** [comment]
@snopoke Any idea why stickler check won't get triggered on this. On the Stickler side , I just turned on the switch for this repo. Did you have to anything else for FP ?

**Comment by snopoke** [comment]
> @snopoke Any idea why stickler check won't get triggered on this. On the Stickler side , I just turned on the switch for this repo. Did you have to do anything else for FP ?

I added this repo to the list of permitted repos in the github app configuration via the 'dimagi' org settings.

**Comment by shubham1g5** [comment]
Thanks @snopoke. Seems to work now.

**Review by snopoke — APPROVED** [review]

**Pull request merged**
