### PR TITLE
update duplication instructions to merge the PR first to avoid errors

### PR DESCRIPTION
**Pull request by Jtang-1**
The starting and ending commit Id is required regardless if PR is merged. Also, clarify instructions to merge the PR first to avoid a stale duplicated PR.

### CODE REVIEW

**Review by minhaminha — APPROVED** [review]

**Comment by minhaminha** [comment]
thank you!

**Comment by Jtang-1** [comment]
duplicate pr 50bbb85 50bbb85

**Comment by Jtang-1** [comment]
duplicate this pr

**Comment by Jtang-1** [comment]
duplicate this PR 50bbb85 50bbb85

**Pull request merged**
