### PR TITLE
Update formplayer to work with Phillip's fixture storage code

### PR DESCRIPTION
**Pull request by wpride**
ibid

### CODE REVIEW

**Comment by amstone326** [comment]
@wpride Has conflicts (although wasn't sure if you intended this for review yet since it doesn't have tags, so sorry if I'm jumping the gun)

**Comment by wpride** [comment]
The bulk of the changes in this PR were in files that've since been moved from `commcare-core` to `formplayer` - just a few helpers left around

**Comment by amstone326** [comment]
@wpride OK, is this ready now then? (no tags still)

**Comment by wpride** [comment]
@amstone326 yes

**Pull request merged**
