### PR TITLE
Suite model change: Adds Endpoint action in detail

### PR DESCRIPTION
**Pull request by shubham1g5**
## Technical Summary

Implementation of 'endpoint actions' for case list fields.[Spec](https://docs.google.com/document/d/1coxsFVCYgaQdxE3rgYikRSgEgistrfIUJuoW5KMiM5w/edit#heading=h.v0u95ovn8r60)

[HQ PR](https://github.com/dimagi/commcare-hq/pull/33560#event-10510560972)

[FP PR](https://github.com/dimagi/formplayer/pull/1472)

### Safety story
Only Model Change with some new api method for FP 

### Automated test coverage
Covered with a new test.

### QA Plan

None

### Special deploy instructions

- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations.

### Review

- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### Duplicate PR
Automatically duplicate this PR as defined in [contributing.md](https://github.com/dimagi/commcare-core/blob/master/.github/contributing.md).

### CODE REVIEW

**Review by Robert-Costello — APPROVED** [review]

**Review by snopoke — APPROVED** [review]

**Comment by shubham1g5** [comment]
duplicate this PR 628e7a8d2b18e56a475a7b7b5f0d520d3ecb7ba0

**Comment by shubham1g5** [comment]
duplicate this PR https://github.com/dimagi/commcare-core/commit/628e7a8d2b18e56a475a7b7b5f0d520d3ecb7ba0

**Comment by Jtang-1** [comment]
duplicate this PR [628e7a8](https://github.com/dimagi/commcare-core/pull/1342/commits/628e7a8d2b18e56a475a7b7b5f0d520d3ecb7ba0)

**Comment by Jtang-1** [comment]
duplicate this PR 628e7a8

**Comment by Jtang-1** [comment]
duplicate this PR 628e7a8 2eacb6b

**Comment by Jtang-1** [comment]
[Looks like 628e7a8d2b18e56a475a7b7b5f0d520d3ecb7ba0 has a conflict with master](https://github.com/dimagi/commcare-core/actions/runs/6461008113/job/17539806754)

**Comment by shubham1g5** [comment]
duplicate this PR 628e7a8d2b18e56a475a7b7b5f0d520d3ecb7ba0 2eacb6b821fb049a1ae7837ae74a1bcb512de9da

**Pull request merged**
