### PR TITLE
Rc/sccs subtitle

### PR DESCRIPTION
**Pull request by Robert-Costello**
## Product Description

This adds results title to case search results screen.

## Technical Summary

jira ticket: https://dimagi-dev.atlassian.net/browse/USH-3323
formplayer PR: (coming soon)

HQ ticket: https://dimagi-dev.atlassian.net/browse/USH-3324

### Safety story

will be tested locally with HQ change
test updated in this PR

### Special deploy instructions

- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations.

### Review

- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### Duplicate PR
Automatically duplicate this PR as defined in [contributing.md](https://github.com/dimagi/commcare-core/blob/master/.github/contributing.md).

### CODE REVIEW

**Review by shubham1g5 — APPROVED** [review]

**Comment by Robert-Costello** [comment]
duplicate this PR

**Comment by shubham1g5** [comment]
@Robert-Costello We should update the specification [here](https://github.com/dimagi/commcare-core/wiki/Suite20#query-datum) in lieu of this change as well.

**Comment by Robert-Costello** [comment]
> We should update the specification [here](https://github.com/dimagi/commcare-core/wiki/Suite20#query-datum) in lieu of this change as well.

gothca, I'll update that spec

**Comment by Robert-Costello** [comment]
duplicate this PR 618e407073a492b78d919470b774e74db99ce216

**Pull request merged**
