### PR TITLE
Mobile  (2.52) to Formplayer Merge

### PR DESCRIPTION
**Pull request by shubham1g5**
Changes seems quite minimal in this direction, mostly error handling and some refactors. Going to request a sanity QA for this. 

QA - https://dimagi-dev.atlassian.net/browse/QA-3246

### CODE REVIEW

**Review by ctsims — APPROVED** [review]
Look  good to me. 

I'm guessing it would be worth QA going through the Form Volatility testing workflows post-merge. They come up quite frequently in false alarms for customers, so since this PR makes changes in the code area if we don't validate that they are still working afterwards it might trigger someone to over-react if a ticket implies an issue.

**Comment by shubham1g5** [comment]
@ctsims I might be missing something, though this doesn't seem to touch any parts relevant to Form Volatility. Are you referring to the `FormMetaIndicatorUtil` class, if so that's not in use on Formplayer yet.

**Comment by ctsims** [comment]
Yeah, I was thinking of the Pragma extraction, I assumed it refactored over to the FormDef, but you're right that it doesn't appear to. Good catch!

**Comment by shubham1g5** [comment]
QA passed on this, going for the merge.

**Comment by ShivamPokhriyal** [comment]
I'm guessing there are a few more commits in 2.52 not included here.

**Comment by shubham1g5** [comment]
yeah we can do another post 2.52 merge for those. This is needed to be in formplayer for https://github.com/dimagi/formplayer/pull/984 , so did an early merge.

**Pull request merged**
