### PR TITLE
Android 13 update

### PR DESCRIPTION
**Pull request by avazirna**
## Product Description
This PR implements changes required to support Android 13. The relevancy here are ICU updates that made handling data symbols more locale-stricter.

### CODE REVIEW

**Comment by avazirna** [comment]
@shubham1g5 I forgot to request your review on this PR.

**Review by shubham1g5 — APPROVED** [review]

**Comment by avazirna** [comment]
> Is this not a mandatory API change ? curious why is not it causing android build to fail on `master` without this merged ?

It is. It can cause errors depending on the device configuration, for instance I have my device language set to `en_ZA` (English - South Africa) and now the abbreviation of `September` appears as `Sept` and not `Sep` (like in the English language), which causes the [parser here](https://github.com/dimagi/commcare-core/blob/ac64d2be3211b49e34fbf85907d8b1430d9a9bbb/src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java#L77) to fail. But in this case, this is only relevant for date months in the `MMM` form.

**Comment by shubham1g5** [comment]
I understand the motivation, though how is it related to Android 13 ?

**Comment by avazirna** [comment]
> I understand the motivation, though how is it related to Android 13 ?

My take is that this is caused by the [ICU changes](https://developer.android.com/about/versions/13/features#unicode) brought by Android 13.

**Comment by avazirna** [comment]
duplicate this PR https://github.com/dimagi/commcare-core/commit/5db37b9158f5c70a3e0514208a96a0403632d563

**Comment by shubham1g5** [comment]
duplicate this PR 5db37b9158f5c70a3e0514208a96a0403632d563

**Pull request merged**
