### PR TITLE
Backmerge Commcare 2.54.0

### PR DESCRIPTION
**Pull request by avazirna**
## Product Description
This PR back-merges changes from CommCare 2.54.0 into the master branch.

### CODE REVIEW

**Review by OrangeAndGreen — APPROVED** [review]

**Comment by shubham1g5** [comment]
@avazirna this needs to be duplicated to formplayer branch as well.

**Comment by avazirna** [comment]
duplicate this https://github.com/dimagi/commcare-core/pull/1430/commits/196966ce6aacf7ca63a745399578eb7a0e0a3712 https://github.com/dimagi/commcare-core/pull/1430/commits/554eb2191d12eee4bdba0e30e4cecf0045bfbfb7

**Comment by avazirna** [comment]
duplicate this https://github.com/dimagi/commcare-core/commit/196966ce6aacf7ca63a745399578eb7a0e0a3712 https://github.com/dimagi/commcare-core/commit/f4d0df4f526b6b097fdd313c6489fd902562246e

**Comment by avazirna** [comment]
duplicate this PR https://github.com/dimagi/commcare-core/commit/196966ce6aacf7ca63a745399578eb7a0e0a3712 https://github.com/dimagi/commcare-core/commit/f4d0df4f526b6b097fdd313c6489fd902562246e

**Comment by avazirna** [comment]
duplicate this PR https://github.com/dimagi/commcare-core/commit/196966ce6aacf7ca63a745399578eb7a0e0a3712 https://github.com/dimagi/commcare-core/pull/1430/commits/554eb2191d12eee4bdba0e30e4cecf0045bfbfb7

**Comment by avazirna** [comment]
duplicate this PR 196966ce6aacf7ca63a745399578eb7a0e0a3712 554eb2191d12eee4bdba0e30e4cecf0045bfbfb7

**Comment by avazirna** [comment]
duplicate this PR 196966c 554eb21

**Comment by avazirna** [comment]
duplicate this PR 196966c 554eb21

**Comment by avazirna** [comment]
duplicate this PR 196966c 554eb21

**Comment by shubham1g5** [comment]
@avazirna If the scripts are failing then you would probably need to copy this manually by cherry-picking the commits.

**Comment by avazirna** [comment]
duplicate this PR 196966c f4d0df4

**Comment by avazirna** [comment]
duplicate this PR 196966c ce48db4

**Pull request merged**
