### PR TITLE
break out regex tests and add a few more

### PR DESCRIPTION
**Pull request by dannyroberts**
in XPathEvalTest

PRing this separately to prove it passes before https://github.com/dimagi/commcare-core/pull/641, which also includes this commit to prove it passes there as well.

### CODE REVIEW

**Comment by dannyroberts** [comment]
Hmm. I'm confused about the build—when does jenkins report the build status?

**Comment by amstone326** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@dannyroberts errr something is broken, looking into it. Thanks for flagging.

**Comment by wpride** [comment]
Copying response from other PR for historical purposes "I did know that; the commcare-core tests also run as part of the formplayer build process so failures would be caught when you tried to update the submodule reference. I can't think of a good reason not to run tests on non-master merges, so happy to make that change"

**Comment by amstone326** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@wpride @dannyroberts Sweet, that was easy. I just added the `formplayer` branch as 1 of the target branches in the jenkins job config, and the tests just ran/passed.

**Pull request merged**
