### PR TITLE
convert result to string

### PR DESCRIPTION
**Pull request by orangejenny**
Error in https://github.com/dimagi/commcare-core/pull/1056, fixed in formplayer in https://github.com/dimagi/commcare-core/pull/1048

### CODE REVIEW

**Review by snopoke — APPROVED** [review]

**Comment by orangejenny** [comment]
@damagatchi retest this please

**Comment by orangejenny** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
@damagatchi retest this please

**Pull request merged**
