### PR TITLE
Bump source compatibility to 1.8

### PR DESCRIPTION
**Pull request by wpride**
I think this is all that needs to happen?

### CODE REVIEW

**Comment by amstone326** [comment]
@wpride What about all of the other changes you had had in this PR https://github.com/dimagi/commcare-android/pull/1964/? including removing retrolambda?

**Comment by amstone326** [comment]
Also you had opened https://github.com/dimagi/commcare-core/pull/783 a little while ago doing the same thing as this PR. Should just close 1 or the other of them

**Comment by wpride** [comment]
It looks like @shubham1g5 's PR took care of them - all those changes appear to be in `master` already

**Comment by amstone326** [comment]
Ohh sweet!

**Pull request merged**
