### PR TITLE
Add PR template

### PR DESCRIPTION
**Pull request by joxl**
## Technical Summary

New PR template for this repository (demonstrated here!).

Ticket: [SAAS-13844](https://dimagi-dev.atlassian.net/browse/SAAS-13844)

### Safety story

PR process only, non-product.

### Automated test coverage

No tests.

### QA Plan

No QA.

### Special deploy instructions
- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions
- [x] This PR can be reverted after deploy with no further considerations.

### Review
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### CODE REVIEW

**Review by orangejenny — DISMISSED** [review]
We don't have a labeled set of risky files for this repo. I don't think the label bot runs.

@shubham1g5 might have thoughts on tweaking this. The main thing that comes to mind for me is explicitly asking about cross-requested PRs, since they're so common here.

**Comment by joxl** [comment]
I'll wait for @shubham1g5's feedback in case he would like to make any modifications before merging this.  Once this is merged I'll create a ticket for an admin to add the [task-list-completed check](https://github.com/stilliard/github-task-list-completed).

**Comment by shubham1g5** [comment]
looks good to me overall except what Jenny already highlighted around risk labels. 

> The main thing that comes to mind for me is explicitly asking about cross-requested PRs, since they're so common here.

agree, this would be nice as well. We can just add a confirmation checkbox saying that cross requested PRs have been mentioned if any.

**Comment by snopoke** [comment]
I don't think the migrations section makes sense for this repo

**Comment by joxl** [comment]
PR description updated with latest version of the template.

**Review by shubham1g5 — APPROVED** [review]

**Pull request merged**
